version: "3"
services:
  server:
    build: ./server
    ports:
      - "50051:50051"
    container_name: "server"
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"